name: Bug report
description: Create a report to help Trainalytics improve.
title: "Bug: Title"
labels: ["Status: Needs Triage"]
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is.
      validations:
          required: true
    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Tell us about your environment.
      validations:
          required: true
    - type: dropdown
      id: engine
      attributes:
          label: Build / Runtime
          multiple: false
          options:
              - Angular CLI App
              - TypeScript
      validations:
          required: true
    - type: input
      id: browsers
      attributes:
          label: Browser(s)
          description: List specific browser(s) the problem occurs on or leave blank if ALL browsers
          placeholder: >
              e.g. Safari 15, iOS 15.4, Chrome 90
    - type: textarea
      id: reproduce-steps
      attributes:
          label: Steps to reproduce the behavior
          description: A clear and concise description of how to make the issue happen.
          placeholder: >
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true
    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: A clear and concise description of what you expected to happen.
      validations:
          required: false
